[package]
name = "zarrs_sqlite"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.91"
futures = "0.3.33"
jiff = { version = "0.2.35", default-features = false, features = [
    "std",
    "alloc",
    "perf-inline",
] }
log = "0.4.33"
r2d2 = { version = "0.8.10", optional = true }
r2d2_sqlite = { version = "0.35.0", optional = true }
rusqlite = { version = "0.40.1", optional = true, features = ["bundled"] }
thiserror = "2.0.19"
tokio = { version = "1.0", features = ["full"], optional = true }
turso = { version = "0.7.1", optional = true }
zarrs_storage = { version = "0.4.5" }

[features]
default = ["backend-rusqlite"]
backend-turso = ["dep:turso", "dep:tokio", "zarrs_storage/async"]
backend-rusqlite = ["dep:rusqlite", "dep:r2d2", "dep:r2d2_sqlite"]

[dev-dependencies]
criterion = { version = "0.8.2", features = ["async_tokio"] }
env_logger = "0.11.11"
temp_testdir = "0.2.3"
zarrs = { version = "0.23.13", default-features = false, features = ["async"] }

[[bench]]
name = "turso_store"
harness = false
required-features = ["backend-turso"]

[[bench]]
name = "rusqlite_store"
harness = false
required-features = ["backend-rusqlite"]

[[example]]
name = "turso_store"
required-features = ["backend-turso"]
